// Carte mondiale : les noms d'époque (1936) des villes et des régions que la
// carte nomme d'après aujourd'hui. Un état qui porte l'un de ces noms, ou qui
// contient une ville de ce nom, reçoit les noms d'époque comme alias : l'IA voit
// « Vilnius [also Wilno] » et un transfert écrit « Wilno » trouve l'état.
//
// Nom d'aujourd'hui (tel que GeoNames l'écrit) → noms de 1936.

export const PERIOD_ALIASES_1936 = Object.freeze({
  // Pologne, Allemagne orientale, Baltes
  Vilnius: ["Wilno", "Vilna"],
  Kaunas: ["Kovno"],
  "Klaipėda": ["Memel"],
  "Gdańsk": ["Danzig"],
  Kaliningrad: ["Königsberg"],
  Sovetsk: ["Tilsit"],
  Chernyakhovsk: ["Insterburg"],
  Olsztyn: ["Allenstein"],
  "Wrocław": ["Breslau"],
  Szczecin: ["Stettin"],
  Koszalin: ["Köslin"],
  Opole: ["Oppeln"],
  Gliwice: ["Gleiwitz"],
  Zabrze: ["Hindenburg"],
  Bytom: ["Beuthen"],
  "Legnica": ["Liegnitz"],
  "Głogów": ["Glogau"],
  "Wałbrzych": ["Waldenburg"],
  Elbląg: ["Elbing"],
  Kwidzyn: ["Marienwerder"],
  Malbork: ["Marienburg"],
  Lviv: ["Lwów", "Lemberg"],
  "Ivano-Frankivsk": ["Stanisławów"],
  Ternopil: ["Tarnopol"],
  Lutsk: ["Łuck"],
  Rivne: ["Równe"],
  Hrodna: ["Grodno"],
  Brest: ["Brześć nad Bugiem", "Brest-Litovsk"],
  Pinsk: ["Pińsk"],
  Chernivtsi: ["Cernăuți", "Czernowitz"],
  "Chișinău": ["Chișinău", "Kishinev"],
  Uzhhorod: ["Ungvár", "Užhorod"],
  "Mukachevo": ["Munkács"],
  Tallinn: ["Reval"],
  Tartu: ["Dorpat"],
  Vyborg: ["Viipuri"],
  Sortavala: ["Sortavala"],
  Pechenga: ["Petsamo"],
  // Union soviétique
  "Saint Petersburg": ["Leningrad"],
  Volgograd: ["Stalingrad"],
  "Nizhniy Novgorod": ["Gorky"],
  "Nizhny Novgorod": ["Gorky"],
  Samara: ["Kuybyshev"],
  Yekaterinburg: ["Sverdlovsk"],
  Tver: ["Kalinin"],
  Donetsk: ["Stalino"],
  Dnipro: ["Dnipropetrovsk"],
  Luhansk: ["Voroshilovgrad"],
  Vladikavkaz: ["Ordzhonikidze"],
  Makhachkala: ["Makhachkala"],
  Almaty: ["Alma-Ata"],
  Bishkek: ["Frunze"],
  Dushanbe: ["Stalinabad"],
  Tbilisi: ["Tiflis"],
  // Europe centrale et balkanique, Méditerranée
  Rijeka: ["Fiume"],
  Pula: ["Pola"],
  Zadar: ["Zara"],
  Koper: ["Capodistria"],
  Bratislava: ["Pressburg", "Pozsony"],
  Liberec: ["Reichenberg"],
  "Ústí nad Labem": ["Aussig"],
  "Karlovy Vary": ["Karlsbad"],
  "Cluj-Napoca": ["Cluj", "Kolozsvár"],
  Oradea: ["Oradea Mare", "Nagyvárad"],
  "Izmir": ["Smyrna"],
  "İzmir": ["Smyrna"],
  Antakya: ["Antioch", "Antioche"],
  "İskenderun": ["Alexandretta"],
  Rhodes: ["Rodi"],
  Tangier: ["Tanger"],
  // Asie, Afrique
  Beijing: ["Peiping", "Peking"],
  Nanjing: ["Nanking"],
  Guangzhou: ["Canton"],
  Shenyang: ["Mukden", "Fengtian"],
  Changchun: ["Hsinking"],
  Harbin: ["Harbin"],
  Chongqing: ["Chungking"],
  Taipei: ["Taihoku"],
  Seoul: ["Keijō", "Keijo"],
  Mumbai: ["Bombay"],
  Chennai: ["Madras"],
  Kolkata: ["Calcutta"],
  Yangon: ["Rangoon"],
  Jakarta: ["Batavia"],
  "Ho Chi Minh City": ["Saigon"],
  Kinshasa: ["Léopoldville"],
  Harare: ["Salisbury"],
  Maputo: ["Lourenço Marques"],
  Yuzhno: ["Toyohara"],
  "Yuzhno-Sakhalinsk": ["Toyohara"],
  Kyzyl: ["Khem-Beldyr"],
});
